# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cv_parser', '0002_auto_20161101_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='id',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='link',
            name='id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='id',
        ),
        migrations.AddField(
            model_name='cv',
            name='guid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='interest',
            name='guid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='link',
            name='guid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='project',
            name='guid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='qualification',
            name='guid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='guid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
